Fix build issue due to ambiguous compare call
qdemonrendershaderprogram.h:461:44: error: ambiguous overload for ‘operator!=’ (operand types are ‘const QDemonRef<QDemonRenderShaderConstantBase>’ and ‘int’)
     bool isValid() const { return constant != 0; }